[package]
name = "nsis-plugin-api"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
widestring = { version = "1.0", default-features = false, features = ["alloc"] }
windows-sys = { workspace = true }
nsis-fn = { path = "../nsis-fn" }
