[package]
name = "nsis-process"
version = "0.2.2"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
nsis-plugin-api = { workspace = true }
windows-sys = { workspace = true }
