[package]
name = "nsis-process"
version = "0.2.2"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[lib]
crate-type = [ "rlib", "cdylib" ]

[dependencies]
pluginapi = { workspace = true }
windows-sys = { workspace = true }
